apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: default
      server: https://kube-controllers.dev:443
    k8sVersion: v1.9.6
    path: default
kind: ksonnet.io/app
name: rt
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  rt:
    protocol: fs
    uri: /Users/ask/src/rt-docker/ksonnet/
version: 0.0.1
